spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/oasis_db
    username: postgres
    password: sayid2003
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 12MB
      max-request-size: 12MB

logging:
  level:
    uz.example.uz.example.oasisuz: trace
